#!/usr/bin/env lua

-- Load the sketchybar-package and prepare the helper binaries
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"
package.path = package.path .. ";/Users/" .. os.getenv("USER") .. "/.config/sketchybar/?.lua"
package.path = package.path .. ";/Users/" .. os.getenv("USER") .. "/.config/sketchybar/?/init.lua"

require("helpers")
require("init")
